// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlIDLcgA-H3BZ_lRQ3o-1QyGqOkVkjhs',
    appId: '1:691455665735:web:63962f0f8b18ac76cbb362',
    messagingSenderId: '691455665735',
    projectId: 'to-do-2c3a7',
    authDomain: 'to-do-2c3a7.firebaseapp.com',
    storageBucket: 'to-do-2c3a7.appspot.com',
    measurementId: 'G-XDDPSEFKKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxIPXtM7PP-aOMiXda9mFytbLsy_uWtpg',
    appId: '1:691455665735:android:54cadd9565049b4bcbb362',
    messagingSenderId: '691455665735',
    projectId: 'to-do-2c3a7',
    storageBucket: 'to-do-2c3a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQee5fkrQ3MWpcRHGc128jklHPAXbSwJY',
    appId: '1:691455665735:ios:f2582bc45c27bde6cbb362',
    messagingSenderId: '691455665735',
    projectId: 'to-do-2c3a7',
    storageBucket: 'to-do-2c3a7.appspot.com',
    iosClientId: '691455665735-s7osldal8g1r1pqujvo9mtf4p9g39uqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQee5fkrQ3MWpcRHGc128jklHPAXbSwJY',
    appId: '1:691455665735:ios:8c78bb4d392e9eeacbb362',
    messagingSenderId: '691455665735',
    projectId: 'to-do-2c3a7',
    storageBucket: 'to-do-2c3a7.appspot.com',
    iosClientId: '691455665735-f14ii3ktgra1maju0pt5su48jikk53gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
